### ISSUE TITLE
Script for Add event to Apple, Google, and Outlook Calendar

### ISSUE THREAD

**Issue by AimeeHapp** [AimeeHapp/live#19]
Note: for after updating the review format.

I am not sure how we'd do this on an elementor page, but I have events like on this page:

https://happivize.com/experience-simply-weigh-less-chameice-daniel/

I'd like to have a link 3 buttons that say Add to Google Calendar, Add to Outlook Calendar, Add to Apple Calendar

where'd we'd just edit the event time and details.

I found this page for google, i'm guessing there would be something similar for the other two somewhere? 

https://developers.google.com/calendar/v3/reference/events/insert#examples

In that example, I could see we would save a row of buttons that have the correct code behind them and then we'd update the details here:

![image](https://user-images.githubusercontent.com/28787692/38167137-5539e988-34fe-11e8-86e4-e4eeb3214875.png)

We would have information that would stay the same each time like the time zone, but we'd update with the link to the URL for that specific event,

Let me know what you think.

**Comment by happivize** [comment]
PS. There are some limited services you can get to do this for you like addevent.com but they require the listener to give the app access to their google calendar for example, which I wouldn't want to do if I were a listener, so I dont' want that to be requirement here.

**Comment by happivize** [comment]
first could you give me an estimate on this? (after reviews are fixed)

**Comment by AimeeHapp** [comment]
closing, using world time buddy
