### ISSUE TITLE
Vendors: Not showing variable products

### ISSUE THREAD

**Issue by AimeeHapp** [AimeeHapp/live#20]
Hey Sergey - do you have time to work on this? I know you have done all the WC Vendor setup for me, nobody else has worked on it but you.

The vendor dashboard does not display variable products sold. I have one vendor, Stacey Mayo, who has 4 variable products for which she is the vendor. It should show each sale of one of the variations separately, but it isn't showing any purchase of any of the variations. We have about 80 so far.

Here is one of her products, she's sold 14 of the 3 variations but nothing shows on her vendor dashboard.

https://happivize.com/product/wealth-acceleration-pkg-a-stacey-mayo/

Can you let me know if/when you could work on this?

Thanks,
Aimee

**Comment by shpp-shablyuk** [comment]
1. You should update this snippet https://prnt.sc/l42l9z
2. You should update this file 'reports.php' in this folder 'themes/flatsome-child/wc-vendors/dashboard/'
[file-for-dashboard.zip](https://github.com/AimeeHapp/live/files/2461162/file-for-dashboard.zip)

3. You should update this file 'orders.php' in this folder 'themes/flatsome-child/wc-vendors/orders/'
[file-for-orders.zip](https://github.com/AimeeHapp/live/files/2461168/file-for-orders.zip)

**Comment by AimeeHapp** [comment]
This is working on live. Note that the previous orders of variable products before fix do not show, but new orders are showing.
