### ISSUE TITLE
Add login to /vendor_dashboard if not logged in

### ISSUE THREAD

**Issue by AimeeHapp** [AimeeHapp/live#21]
We used to send our vendors to:

https://happivize.com/vendor_dashboard 

and it had a login form, but now it doesn't, can you add one there if it not logged in and once they do login they are shown their vendor dashboard?

**Comment by shpp-shablyuk** [comment]
You can try to set this option 
![screenshot 46](https://user-images.githubusercontent.com/13415218/46731023-4cc3ec00-cc92-11e8-8c84-4da56c728281.png)

**Comment by AimeeHapp** [comment]
Yes the page /vendor_dashboard works as it is supposed to if you are logged in and assigned a Vendor Role. But if you are NOT logged in, it just shows a few rows of white space. What I'd like it to do is 

a) if someone is not logged in, that the page display the login form so that they can login right there 
b) and then after submitting their info it refreshes and now shows the Vendor Dashboard

Or, if they aren't logged in and they try to go to it, it redirects them to a login page and then after entering login it takes them to the Vendor Dashboard page.

Just some way where we can give our vendors one link, if they are logged in they see their dashboard, if they are not, they are prompted to login and immediately shown the dashboard without having to do anything else

Do you have any ideas?

**Comment by shpp-shablyuk** [comment]
Done. Check, please.

**Comment by AimeeHapp** [comment]
yes that works. how do i update on live?

**Comment by shpp-shablyuk** [comment]
![screenshot 47](https://user-images.githubusercontent.com/13415218/46755616-2e7be180-ccce-11e8-9ae7-97e504fc4eab.png)

**Comment by AimeeHapp** [comment]
added to live, thanks
