### ISSUE TITLE
Vendor: Full Name not showing in Show Orders

### ISSUE THREAD

**Issue by AimeeHapp** [AimeeHapp/live#22]
Decided to create a new issue for this, tho it's related to the last one.

When I click Show Orders the Full Name is blank:

![image](https://user-images.githubusercontent.com/28787692/46761850-923ce500-cca3-11e8-8d39-1004a5120f4d.png)

**Comment by shpp-shablyuk** [comment]
Check, please.

**Comment by AimeeHapp** [comment]
Yes it is working now, how do I update on live?

**Comment by shpp-shablyuk** [comment]
![screenshot 53](https://user-images.githubusercontent.com/13415218/46881251-a1fb2b80-ce53-11e8-914e-5b92812aabe6.png)

**Comment by AimeeHapp** [comment]
snippet updated on live and confirmed working, thanks
