### ISSUE TITLE
Don't Display Price "From: $xx" on Grouped Products

### ISSUE THREAD

**Issue by AimeeHapp** [AimeeHapp/live#24]
Hey Sergey, I wondered if you could work on this soon, if you could create a snippet where when I add a grouped product ID to it, that grouped product won't show the From: $XX under the title. Just not displaying anything there. The line would just be gone.

![image](https://user-images.githubusercontent.com/28787692/50224334-a9ffac00-036b-11e9-97ea-bd5b76693f72.png)

 If you check out the snippet:

One-time Change to Grouped Product From Pricing - Wealth Acceleration

There he changed it to make it so I could put a range like $29-$127, I don't know if it will be easier to edit that or create your own. I am hoping it will be snippet only and not need to change files?

The ID is you would put a grouped product ID number there to delete it, and then I could just add additional grouped Product IDs when I also dont' want them to have it display. Does that make sense?

**Comment by shpp-shablyuk** [comment]
Hello Aimee,
I can't begin today, maybe tomorrow.

**Comment by AimeeHapp** [comment]
When you say "maybe" tomorrow, how likely is that?

**Comment by shpp-shablyuk** [comment]
I think I can work with your task tomorrow. 
Do you want to add the ability to hide the "From $xx" in group products?

**Comment by AimeeHapp** [comment]
Ok thanks. I just want a snippet that I can add multiple Group Product IDs too, I don't need it to be fancy and have a checkbox in the Edit Product page. I wont' need it very often.

**Comment by shpp-shablyuk** [comment]
Done
![snippets happivize wordpress](https://user-images.githubusercontent.com/13415218/50281936-ce39b680-0459-11e9-88c8-c42c0a1b5e97.png)

**Comment by shpp-shablyuk** [comment]
![digestion support with spirit mia den haan happivize](https://user-images.githubusercontent.com/13415218/50281965-e27db380-0459-11e9-86b5-de471bba5bed.png)

![wealth acceleration stacey mayo happivize](https://user-images.githubusercontent.com/13415218/50281994-f32e2980-0459-11e9-88b4-5f25aea5e52d.png)

**Comment by shpp-shablyuk** [comment]
![edit snippet happivize wordpress](https://user-images.githubusercontent.com/13415218/50282066-4607e100-045a-11e9-8488-48d9f7974f4a.png)

**Comment by shpp-shablyuk** [comment]
Yes

**Comment by AimeeHapp** [comment]
Thank you, this is working.
